version: '3.1'
services:
  trim_db:
    image: mongo:4-xenial
    container_name: trim_db
    command: --smallfiles
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      TZ: 'Europe/Moscow'
  trim_express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: trim_db
  trim_influx:
    image: influxdb:1.7
    ports:
      - 8086:8086
    volumes:
      - ./influx-data:/var/lib/influxdb
  trim_influxui:
    image: sillydong/influxdb-ui
    ports:
      - 8083:80
