apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
  namespace: trimmer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: app
        image: piterjs/trimmer-app:v0.0.1-{{truncate build.commit 8}}
        ports:
        - containerPort: 3000
        env:
        - name: "PORT"
          value: "3000"
        - name: "MONGO_URL"
          value: "mongodb://db.trimmer.svc.cluster.local:27017/app"
        volumeMounts:
        - mountPath: /app/secrets
          readOnly: true
          name: client
      volumes:
      - name: client
        secret:
          secretName: client
