apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
  namespace: trimmer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: app
        image: piterjs/trimmer-app:v0.0.1-{{truncate build.commit 8}}
        ports:
        - containerPort: 3000
        env:
        - name: "PORT"
          value: "3000"
        - name: "INFLUX_HOST"
          value: "influx.trimmer.svc.cluster.local"
        - name: "INFLUX_PORT"
          value: "8086"
        - name: "INFLUX_DB"
          value: "watcher"
        - name: "MONGO_URL"
          value: "mongodb://db.trimmer.svc.cluster.local:27017/app"
        - name: "AUTHORIZATION_URL"
          valueFrom:
            configMapKeyRef:
              name: app
              key: authorizationURL
        - name: "TOKEN_URL"
          valueFrom:
            configMapKeyRef:
              name: app
              key: tokenURL
        - name: "CLIENT_ID"
          valueFrom:
            configMapKeyRef:
              name: app
              key: clientID
        - name: "CLIENT_SECRET"
          valueFrom:
            configMapKeyRef:
              name: app
              key: clientSecret
        - name: "CALLBACK_URL"
          valueFrom:
            configMapKeyRef:
              name: app
              key: callbackURL
        - name: "OAUTHBASE_URL"
          valueFrom:
            configMapKeyRef:
              name: app
              key: baseURL
        volumeMounts:
        - mountPath: /app/secrets
          readOnly: true
          name: client
      volumes:
      - name: client
        secret:
          secretName: client
