apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: watcher
  labels:
    app: watcher
  namespace: trimmer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: watcher
  template:
    metadata:
      labels:
        app: watcher
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: watcher
        image: piterjs/trimmer-watcher:v0.0.1-{{truncate build.commit 8}}
        env:
        - name: "MONGO_URL"
          value: "mongodb://db.trimmer.svc.cluster.local:27017/app"
        - name: "INFLUX_HOST"
          value: "influx.trimmer.svc.cluster.local"
        - name: "INFLUX_PORT"
          value: "8086"
        - name: "INFLUX_DB"
          value: "watcher"
        volumeMounts:
        - mountPath: /app/secrets
          readOnly: true
          name: client
      volumes:
      - name: client
        secret:
          secretName: client
